mumoshu/variant

pkg/steps/script_step.go
Added parameters for overwriting docker `--entrypoint` option.
```
runner:
image: mesosphere/aws-cli:1.14.5
command: /bin/sh
args: [-c]
script: echo 111;
```
```
DEBU[0000] script step started                           cmd="[docker run --rm -i --entrypoint  mesosphere/aws-cli:1.14.5 /bin/sh -c echo 111;]"
INFO[0000] 111    
```
=> support runner.entrypoint parameter

pkg/steps/script_step.go
An error below has occured when running `make build` or `go get -u github.com/mumoshu/variant`.
```
%  make build
test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)" || test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -w {} + | tee /dev/stderr)"
mkdir -p dist/
go build -ldflags "-X '_/Users/hashimoto-takuma/go/src/github.com/mumoshu/variant/cli/version.VERSION='" -o dist//var .
pkg/steps/script_step.go:184:23: cannot use c.Entrypoint (type *string) as type string in append
make: *** [dist] Error 2
%  go get -u github.com/mumoshu/variant
go/src/github.com/mumoshu/variant/pkg/steps/script_step.go:184:23: cannot use c.Entrypoint (type *string) as type string in append
```
- ref. …
=> fix c.Entrypoint type error

Makefile, pkg/steps/script_step.go, test/integration/containerized-task-autoenv
support `runner.env`option.
```
runner-env:
runner:
image: "alpine:3.7"
command: sh
args: [-c]
env:
FOO: foo
script: |
env | grep "FOO=foo"
```
and, We have made it possible to expand environment variables and `autoenv` parameters with some runner options.
=> support runner env

Makefile, pkg/application.go, test/integration/multistage-task-parameters
fixes parameters are not set in multistage.
```
tasks:
param1:
script: |
echo foo
param2:
options:
- name: param1
required: true
script: |
echo {{ get "param1" }}
test:
options:
- name: param2
required: true
script: |
echo {{ get "param2" }}
```
We have made it possible to call tasks in multistage like `test -> param2 -> param1`.
=> fixes parameters are not set in multistage

Makefile, pkg/task_runner.go, test/integration/params-type-autoenv
When `autoenv` is set to `true` with the parameter of `integer`, `autoenv` becomes invalid.
```
integer-env:
options:
- name: foo
type: integer
default: 1
autoenv: true
script: |
env // FOO is not found
```
So we changed it to work according to the type we support.
https://github.com/mumoshu/variant/blob/ef7e10bbe31e344b7156acd4693417d97e52f18f/pkg/application.go#L362
=> fixes support interger and bool parameter in autoenv

pkg/steps/script_step.go
I want to connect to the host network as a use case.
For example, it connects to kubernetes launched into host network such as kubectl and helm.
```
runner:
image: chatwork/helm
entrypoint: ''
command: sh
args: [-c]
net: host
volumes:
- $HOME/.kube:/root/.kube
- $HOME/.helm:/root/.helm
script: |
helm ls --kube-context docker-for-desktop
```
=> support runner.net option

pkg/steps/script_step.go
We have to do `cd /[mount-dir]` with Docke Image which does not specify `WORKDIR`.
Since this is troublesome I have support `runner.workdir`.
```
runner:
image: alpine
command: sh
args: [-c]
volumes:
- $PWD:/alpine
workdir: /alpine
script: |
pwd # -> /alpine
```
=> support runner.workdir option

examples/codebuild/bin/codebuildsh
By describing environment variables with AWS CLI shorthand syntax in `envfile` for CodeBuild task runner, we've made it possible to set these variables in the CodeBuild projects.
e.g.
```bash
...
subnets=subnet-12345678
environment=[{name=GOPATH,value=/go,type=PLAINTEXT},{name=FOO,value=BAR,type=PLAINTEXT}]
```
```yaml
runner:
image: "mumoshu/variant-runner-codebuild:canary"
envfile: ./codebuild.env
volumes:
- $HOME/.aws/credentials:/root/.aws/credentials
script: |
echo $FOO
```
```
...
INFO[0051] + sed -n '/Running command/,$p'               stream=stderr
INFO[0051] + jq -jr '.events[] | select(true) | .message' log-events.json  stream=stderr
INFO[0051] + tac                                         stream=stderr
INFO[0051] BAR                                           stream=stdout …
```
=> feat: enable to set environment variables in CodeBuild projects

pkg/cli/env/env.go
changed the resolve order of envfile.
1. `.[command]env`
2. `.variantenv`
3. `.varenv`
We have use cases of multiple variant commands.
```
.
├── .command1env
├── .command2env
├── .command3env
├── command1
├── command2
└── command3
```
However, it is very difficult to manage multiple envfiles.
So we made it read common `.variantenv` and `.varenv`.
=> change the resolve order of envfile

pkg/util/maputil/maputil.go
If the `type: Object` parameter value is `merge`, map will be evaluated as `map[interface{}]interface{}` and an error will occur.
```yaml
#!/usr/bin/env variant
tasks:
foo:
parameters:
- name: obj
type: object
script: |
cat <<EOS
{{ merge (readFile (get "cmd") | fromYaml) (get "obj") | toYaml }}
EOS
bar:
steps:
- task: foo
arguments:
obj: |
{
"tasks": {
"bar": 1
}
}
```
```bash
$  ./cmd bar
maputil manics! unexpected type of value in map: dest=map[tasks:map[bar:map[steps:[map[task:foo arguments:map[obj:{
"tasks": {
"bar": 1
}
}]]]] foo:map[parameters:[map[name:obj type:object]] script:cat <<EOS
{{ merge (readFile (get "cmd") | fromYaml) (get "obj") | toYaml }}
EOS
]]], k=tasks, dest[k]=map[foo:map[parameters:[map[name:obj type:object]] script:cat <<EOS
{{ merge (readFile (get "cmd") | …
```
=> fixes an issue where merging `map[interface{}]interface{}` caused an error

pkg/application.go, pkg/variant.go, pkg/variant_text_log_formatter.go
**WHAT:**
Add custom colors for log messages.
**WHY:**
For some cases, we want to allow to set custom colors for every type of log messages (panic, fatal, error, warn, info, debug, trace). For example, many CLI commands output info messages into STDERR which is echoed as "red" from the variant ("warn" level in variant) and we want to be able to set another color for these messages to be able to distinguish them from the actual errors.
---
WIth this PR we'll be able to set custom colors for the log messages through **viper** params (e.g. env var VARIANT_LOG_COLOR_WARN=light_blue, etc).
=> feat: Add custom log colors

Makefile, pkg/step_execution_context.go, pkg/task_runner.go, pkg/task_template.go, test/integration/step-result-as-param/Variantfile
Once you `name` a step within `steps` section of your `task`, next or following steps can refer to the output of the named step:
```
steps:
- name: res
task: duplicate
arguments:
input: "{{.argument}}"
```
As the first step in the above example is named `res`, the subsequent step can refer to the output of the step by `res`, like:
```
- script: |
echo "Double {{.argument}} will be: {{.res}}"
```
Resolves #73
=> feat: Named step outputs are now parameters

pkg/variant.go
Fix environment-specific file loading when 'config-file' option is set.
Closes #78
=> [#78] fix: environment-specific file loading

pkg/variant.go
Solves #81 
Now you can use the Viper-based ```hide_extra_cmds``` configuration entity to control if extra commands entries should be hidden from ```help```, like:
```
VARIANT_HIDE_EXTRA_CMDS=true variant
```
=> feat: Option to not pollute arguments

pkg/variant.go
This variable is never used, so it was removed to avoid confusion.
=> Remove unused viper variable

pkg/application.go, pkg/viper.go
I don't see any reason to introduce an additional and restrictive layer (interface) for the Viper usage, so I've removed it.
=> Remove restrictive Viper interface as not needed.

pkg/task_runner.go
I changed the parameter name to Camel Case with this change.
https://github.com/mumoshu/variant/commit/01bb4e1c8787d98d13bf0d4fed7fd3dcec32b1b8
```
parameters:
- name: awsAccessKeyId
- name: awsSecretAccessKey
- name: awsProfile
- name: awsDefaultRegion
```
However, the environment variable name generated by autoenv has become a string of UpperCase.
```
Generated autoenv: map[AWSACCESSKEYID: AWSDEFAULTREGION: AWSPROFILE: AWSSECRETACCESSKEY: CMD:./variantfile ENV:default]
```
I think I should be `AWS_ACCESS_KEY_ID` instead of `AWSACCESSKEYID`.
=> convert camelName to CAMEL_NAME with autoenv.

Makefile, pkg/cobra.go, pkg/task_runner.go, pkg/util/stringutil/stringutil.go, test/integration/autoenv_task_step
`s3Bucket` parameter are converted to `--s-3bucket` for arguments and `S_3BUCKET` for environment variables.
```
#!/usr/bin/env variant
tasks:
foo:
parameters:
- name: s3Bucket
default: ""
autoenv: true
script: |
echo {{ get "s3Bucket" }}
```
```
$ ./hoge foo --help
Usage:
hoge foo [s3Bucket] [flags]
Flags:
-h, --help               help for foo
--s-3bucket string   s3Bucket
```
```
Generated autoenv: map[CMD:./hoge ENV:cwk8s111-test S_3BUCKET:]
````
I think that it is natural that the argument is converted to `--s3-bucket` and the environment variable is converted to `S3_BUCKET`.
=> fixes parameter s3Bucket to be the argument --s3-bucket

Makefile, pkg/application.go, pkg/variant.go, test/integration/param-val-from-specific-config/mycmd, test/integration/param-val-from-specific-config/myconfig.yaml
Running `mycmd -c config.yaml` doesn't seem to correctly load settings from the file, while the default config `mycmd.yaml` is loaded without any problem.
=> fix: regression in loading params from non-default config file

README.md
(Documentation for VARIANT_RUN_TRIM_PREFIX still looks wrong to me.)
=> Fix typo and  docs for VARIANT_RUN
